FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.23.1-alpine

RUN apk add bash

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY certs/* /etc/ssl

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/dist/* ./
COPY *.sh ./

RUN chmod +x *.sh

CMD ["/usr/share/nginx/html/nginx_start.sh"]
