version: '3.8'
services:
  frontend:
    image: 'interactive-comments-section-front-dev'
    build: ./client
    ports:
      - 4242:4242
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    env_file:
      - ./client/.env
