version: '3.8'
services:
  frontend:
    image: 'interactive-comments-section-front-prod'
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./client/.env
