version: '3.8'
services:
  frontend:
    image: 'ics-front-prod'
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env
