name: CD interactive comments section workflow
run-name: ${{ github.actor }} is activating CI process

on:
  push:
    branches:
      - dev
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
